// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPsTAdRjVDqX3Jg6dLZ3peNy7G6KSArk',
    appId: '1:851457401257:web:55e529c2b6186c4a1c64b8',
    messagingSenderId: '851457401257',
    projectId: 'form-feedback-7a3b8',
    authDomain: 'form-feedback-7a3b8.firebaseapp.com',
    storageBucket: 'form-feedback-7a3b8.firebasestorage.app',
    measurementId: 'G-MN04914Q9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMniTa7ovKsq7aEK4Fxmkc_l_MKpC3tRM',
    appId: '1:851457401257:android:a7407ce18d4cc1c81c64b8',
    messagingSenderId: '851457401257',
    projectId: 'form-feedback-7a3b8',
    storageBucket: 'form-feedback-7a3b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBooos-mRScPqM36b9lGl6PyoGLY0F9MgA',
    appId: '1:851457401257:ios:e2810dc8690140431c64b8',
    messagingSenderId: '851457401257',
    projectId: 'form-feedback-7a3b8',
    storageBucket: 'form-feedback-7a3b8.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBooos-mRScPqM36b9lGl6PyoGLY0F9MgA',
    appId: '1:851457401257:ios:e2810dc8690140431c64b8',
    messagingSenderId: '851457401257',
    projectId: 'form-feedback-7a3b8',
    storageBucket: 'form-feedback-7a3b8.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPsTAdRjVDqX3Jg6dLZ3peNy7G6KSArk',
    appId: '1:851457401257:web:bffa0aa4395b61201c64b8',
    messagingSenderId: '851457401257',
    projectId: 'form-feedback-7a3b8',
    authDomain: 'form-feedback-7a3b8.firebaseapp.com',
    storageBucket: 'form-feedback-7a3b8.firebasestorage.app',
    measurementId: 'G-Q8K5CH61JH',
  );
}
